### ISSUE TITLE
Invalid Zone

### ISSUE THREAD

**Issue by jrdean** [digitalcraig/adt-pulse-mqtt#15]
I can't get this add-on to work anymore. I don't believe anything changed with my installation that I'm aware of. I did restore to a previous snapshot that was known working with adt-pulse-mqtt. I didn't upgraded to the 107 update of HA that was released today. I'm still using 106.6. 

I never paid attention to the website, but I do see "Web Portal version: |   | 18.0.0-78". I wonder if ADT updated that and it broke something in this add on. Any help is appreciated because I find this to be one of my most useful add-ons and several automations are implemented based on door and motion sensors from adt-pulse.

The error log shows 

3/18/2020, 8:29:57 PM Pulse: Invalid Zone JSONTypeError: Cannot read property 'items' of null
    at Request._callback (/usr/src/app/adt-pulse.js:184:12)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:223:5)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:312:28)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

**Comment by mrjackyliang** [comment]
ADT updated the zone file and turned it into `null`. This plugin is also using the same script as my plugin, `homebridge-adt-pulse`.

**Comment by mrjackyliang** [comment]
I have fixed the problem on my plugin `homebridge-adt-pulse`.

If anyone would like to contribute to `adt-pulse-mqtt` and fix this issue, you may witness the fix in [this file](https://github.com/mrjackyliang/homebridge-adt-pulse/blob/master/api.js).

The function name is `getZoneStatusOrb`.

**Comment by digitalcraig** [comment]
@mrjackyliang Thanks, I'll take a look. Feel free to submit a pull request as well.

**Comment by digitalcraig** [comment]
New version on Docker Hub if you are running in Docker. If you are using my Hass.io addon repository,  it should show an update available.
