### ISSUE TITLE
Under Home Assistant 2020.12.7 Getting Error at Startup

### ISSUE THREAD

**Issue by pickerin** [digitalcraig/adt-pulse-mqtt#29]
@digitalcraig Craig, I've recently come back to your ADT Pulse MQTT integration from the non-MQTT one.  That one wouldn't register anything but contact sensors and I have an ADT Garage Opener.

Your integration previously worked well after configuration, including allowing me to control my Garage Opener and know if it was open or not.  

I re-installed the integration, but it's failing to launch with the following error:

`12/27/2020, 5:32:21 PM Pulse.getZoneStatus(via Orb): Getting Zone Statuses
Device callback{"name":"Garage Door","serialnumber":"REDACTED","state":1}
Device callback{"name":"Garage Door","serialnumber":"REDACTED","state":1}
/usr/src/app/node_modules/cheerio/lib/parse.js:38
      content.forEach(function (node) {
              ^

TypeError: content.forEach is not a function
    at parse (/usr/src/app/node_modules/cheerio/lib/parse.js:38:15)
    at Function.exports.load (/usr/src/app/node_modules/cheerio/lib/static.js:39:14)
    at /usr/src/app/adt-pulse.js:232:34
    at arrayMap (/usr/src/app/node_modules/lodash/lodash.js:639:23)
    at Function.map (/usr/src/app/node_modules/lodash/lodash.js:9580:14)
    at Request._callback (/usr/src/app/adt-pulse.js:231:24)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pulse-adt-mqtt@2.3.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pulse-adt-mqtt@2.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-28T01_32_21_366Z-debug.log
[cmd] /run.sh exited 1`

Contents of the mentioned debug log:

`
14 verbose pkgid pulse-adt-mqtt@2.3.0
15 verbose cwd /usr/src/app
16 verbose Linux 5.4.0-58-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v12.18.4
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error pulse-adt-mqtt@2.3.0 start: `node server.js`
22 error Exit status 1
23 error Failed at the pulse-adt-mqtt@2.3.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by digitalcraig** [comment]
I'm not sure how long since you last used this plugin, but there was a pretty significant rewrite which occurred when ADT deprecated the method we were using to get the status. We had to switch to parsing HTML of the status page instead. The error you are seeing is in the code that does the parsing of the HTML.

Can you grab the source of this page after you login into the portal? https://portal.adtpulse.com/myhome/20.0.0-244/ajax/orb.jsp In particular, I need to see the section which includes the status table called orbSensorsList. I suspect there is a device type we weren't expecting.

**Comment by digitalcraig** [comment]
Reference issue #19 as well.

**Comment by pickerin** [comment]
Here is the full table in question:
```
<div id="orbSensorsList" style="height:114px;position:relative;overflow:auto;overflow-y:auto;overflow-x:auto;text-align:left;">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr class="p_rowl" style="cursor:pointer;" onmouseover="setbg(this,'p_rowh')" onmouseout="setbg(this,'p_rowl')"><td><table border=0 cellspacing=0 cellpadding=0 width=100%><tr class='p_listRow'><td width="14" style="overflow: hidden;" class='p_iconCellSummary' onClick="launchDetailsWindow('RmFtaWx5IE1vdGlvbiBEZXRlY3Rvcg==', 1)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><span class="devStatIcon" title="Last Event: Today&nbsp;7:04&nbsp;AM"><canvas icon="devStatMotion" class="p_ic_icon_device" width="13" height="13"></canvas><td width=9 onClick="launchDetailsWindow('RmFtaWx5IE1vdGlvbiBEZXRlY3Rvcg==', 1)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><img src="/myhome/20.0.0-244/images/spacer.gif" border=0 width=1 height=2></td><td class='p_listRow' onClick="launchDetailsWindow('RmFtaWx5IE1vdGlvbiBEZXRlY3Rvcg==', 1)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><a class="p_deviceNameText" href="javascript:launchDetailsWindow('RmFtaWx5IE1vdGlvbiBEZXRlY3Rvcg==', 1)">Family Motion Detector</a>&nbsp; <span class="p_grayNormalText">Zone&nbsp;2</span></td><td class='p_listRow' valign=middle align=right onClick="launchDetailsWindow('RmFtaWx5IE1vdGlvbiBEZXRlY3Rvcg==', 1)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'">Motion&nbsp;</td></tr></tr></table></td></tr>
<tr class="p_rowd" style="cursor:pointer;" onmouseover="setbg(this,'p_rowh')" onmouseout="setbg(this,'p_rowd')"><td><table border=0 cellspacing=0 cellpadding=0 width=100%><tr class='p_listRow'><td width="14" style="overflow: hidden;" class='p_iconCellSummary' onClick="launchDetailsWindow('RGluaW5nIExpdmluZyBXaW5kb3c=', 168)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><span class="devStatIcon" title="Last Event: 12/21&nbsp;4:08&nbsp;PM"><canvas icon="devStatOK" class="p_ic_icon_device" width="13" height="13"></canvas><td width=9 onClick="launchDetailsWindow('RGluaW5nIExpdmluZyBXaW5kb3c=', 168)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><img src="/myhome/20.0.0-244/images/spacer.gif" border=0 width=1 height=2></td><td class='p_listRow' onClick="launchDetailsWindow('RGluaW5nIExpdmluZyBXaW5kb3c=', 168)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><a class="p_deviceNameText" href="javascript:launchDetailsWindow('RGluaW5nIExpdmluZyBXaW5kb3c=', 168)">Dining Living Window</a>&nbsp; <span class="p_grayNormalText">Zone&nbsp;3</span></td><td class='p_listRow' valign=middle align=right onClick="launchDetailsWindow('RGluaW5nIExpdmluZyBXaW5kb3c=', 168)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'">Closed&nbsp;</td></tr></tr></table></td></tr>
<tr class="p_rowl" style="cursor:pointer;" onmouseover="setbg(this,'p_rowh')" onmouseout="setbg(this,'p_rowl')"><td><table border=0 cellspacing=0 cellpadding=0 width=100%><tr class='p_listRow'><td width="14" style="overflow: hidden;" class='p_iconCellSummary' onClick="launchDetailsWindow('RG93bnN0YWlycyBQZXJpbWV0ZXI=', 24)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><span class="devStatIcon" title="Last Event: Yesterday&nbsp;10:12&nbsp;PM"><canvas icon="devStatOK" class="p_ic_icon_device" width="13" height="13"></canvas><td width=9 onClick="launchDetailsWindow('RG93bnN0YWlycyBQZXJpbWV0ZXI=', 24)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><img src="/myhome/20.0.0-244/images/spacer.gif" border=0 width=1 height=2></td><td class='p_listRow' onClick="launchDetailsWindow('RG93bnN0YWlycyBQZXJpbWV0ZXI=', 24)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><a class="p_deviceNameText" href="javascript:launchDetailsWindow('RG93bnN0YWlycyBQZXJpbWV0ZXI=', 24)">Downstairs Perimeter</a>&nbsp; <span class="p_grayNormalText">Zone&nbsp;4</span></td><td class='p_listRow' valign=middle align=right onClick="launchDetailsWindow('RG93bnN0YWlycyBQZXJpbWV0ZXI=', 24)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'">Closed&nbsp;</td></tr></tr></table></td></tr>
<tr class="p_rowd" style="cursor:pointer;" onmouseover="setbg(this,'p_rowh')" onmouseout="setbg(this,'p_rowd')"><td><table border=0 cellspacing=0 cellpadding=0 width=100%><tr class='p_listRow'><td width="14" style="overflow: hidden;" class='p_iconCellSummary' onClick="launchDetailsWindow('RnJvbnQgR2FyYWdlIERvb3I=', 24)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><span class="devStatIcon" title="Last Event: Yesterday&nbsp;10:13&nbsp;PM"><canvas icon="devStatOK" class="p_ic_icon_device" width="13" height="13"></canvas><td width=9 onClick="launchDetailsWindow('RnJvbnQgR2FyYWdlIERvb3I=', 24)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><img src="/myhome/20.0.0-244/images/spacer.gif" border=0 width=1 height=2></td><td class='p_listRow' onClick="launchDetailsWindow('RnJvbnQgR2FyYWdlIERvb3I=', 24)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><a class="p_deviceNameText" href="javascript:launchDetailsWindow('RnJvbnQgR2FyYWdlIERvb3I=', 24)">Front Garage Door</a>&nbsp; <span class="p_grayNormalText">Zone&nbsp;1</span></td><td class='p_listRow' valign=middle align=right onClick="launchDetailsWindow('RnJvbnQgR2FyYWdlIERvb3I=', 24)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'">Closed&nbsp;</td></tr></tr></table></td></tr>
<tr class="p_rowl" style="cursor:pointer;" onmouseover="setbg(this,'p_rowh')" onmouseout="setbg(this,'p_rowl')"><td><table border=0 cellspacing=0 cellpadding=0 width=100%><tr class='p_listRow'><td width="14" style="overflow: hidden;" class='p_iconCellSummary' onClick="launchDetailsWindow('S2l0Y2hlbiBTbW9rZQ==', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><span class="devStatIcon" title="Last Event: 5/1&nbsp;6:32&nbsp;PM"><canvas icon="devStatOK" class="p_ic_icon_device" width="13" height="13"></canvas><td width=9 onClick="launchDetailsWindow('S2l0Y2hlbiBTbW9rZQ==', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><img src="/myhome/20.0.0-244/images/spacer.gif" border=0 width=1 height=2></td><td class='p_listRow' onClick="launchDetailsWindow('S2l0Y2hlbiBTbW9rZQ==', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><a class="p_deviceNameText" href="javascript:launchDetailsWindow('S2l0Y2hlbiBTbW9rZQ==', 672)">Kitchen Smoke</a>&nbsp; <span class="p_grayNormalText">Zone&nbsp;10</span></td><td class='p_listRow' valign=middle align=right onClick="launchDetailsWindow('S2l0Y2hlbiBTbW9rZQ==', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'">Okay&nbsp;</td></tr></tr></table></td></tr>
<tr class="p_rowd" style="cursor:pointer;" onmouseover="setbg(this,'p_rowh')" onmouseout="setbg(this,'p_rowd')"><td><table border=0 cellspacing=0 cellpadding=0 width=100%><tr class='p_listRow'><td width="14" style="overflow: hidden;" class='p_iconCellSummary' onClick="launchDetailsWindow('TWFzdGVyIEJlZHJvb20gV2luZG93', 336)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><span class="devStatIcon" title="Last Event: 12/17&nbsp;10:53&nbsp;AM"><canvas icon="devStatOK" class="p_ic_icon_device" width="13" height="13"></canvas><td width=9 onClick="launchDetailsWindow('TWFzdGVyIEJlZHJvb20gV2luZG93', 336)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><img src="/myhome/20.0.0-244/images/spacer.gif" border=0 width=1 height=2></td><td class='p_listRow' onClick="launchDetailsWindow('TWFzdGVyIEJlZHJvb20gV2luZG93', 336)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><a class="p_deviceNameText" href="javascript:launchDetailsWindow('TWFzdGVyIEJlZHJvb20gV2luZG93', 336)">Master Bedroom Window</a>&nbsp; <span class="p_grayNormalText">Zone&nbsp;6</span></td><td class='p_listRow' valign=middle align=right onClick="launchDetailsWindow('TWFzdGVyIEJlZHJvb20gV2luZG93', 336)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'">Closed&nbsp;</td></tr></tr></table></td></tr>
<tr class="p_rowl" style="cursor:pointer;" onmouseover="setbg(this,'p_rowh')" onmouseout="setbg(this,'p_rowl')"><td><table border=0 cellspacing=0 cellpadding=0 width=100%><tr class='p_listRow'><td width="14" style="overflow: hidden;" class='p_iconCellSummary' onClick="launchDetailsWindow('VXAgSGFsbCBNb3Rpb24=', 1)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><span class="devStatIcon" title="Last Event: Today&nbsp;6:46&nbsp;AM"><canvas icon="devStatOK" class="p_ic_icon_device" width="13" height="13"></canvas><td width=9 onClick="launchDetailsWindow('VXAgSGFsbCBNb3Rpb24=', 1)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><img src="/myhome/20.0.0-244/images/spacer.gif" border=0 width=1 height=2></td><td class='p_listRow' onClick="launchDetailsWindow('VXAgSGFsbCBNb3Rpb24=', 1)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><a class="p_deviceNameText" href="javascript:launchDetailsWindow('VXAgSGFsbCBNb3Rpb24=', 1)">Up Hall Motion</a>&nbsp; <span class="p_grayNormalText">Zone&nbsp;9</span></td><td class='p_listRow' valign=middle align=right onClick="launchDetailsWindow('VXAgSGFsbCBNb3Rpb24=', 1)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'">No Motion&nbsp;</td></tr></tr></table></td></tr>
<tr class="p_rowd" style="cursor:pointer;" onmouseover="setbg(this,'p_rowh')" onmouseout="setbg(this,'p_rowd')"><td><table border=0 cellspacing=0 cellpadding=0 width=100%><tr class='p_listRow'><td width="14" style="overflow: hidden;" class='p_iconCellSummary' onClick="launchDetailsWindow('VXAgSGFsbCBTbW9rZQ==', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><span class="devStatIcon" title="Last Event: 12/14&nbsp;12:32&nbsp;PM"><canvas icon="devStatOK" class="p_ic_icon_device" width="13" height="13"></canvas><td width=9 onClick="launchDetailsWindow('VXAgSGFsbCBTbW9rZQ==', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><img src="/myhome/20.0.0-244/images/spacer.gif" border=0 width=1 height=2></td><td class='p_listRow' onClick="launchDetailsWindow('VXAgSGFsbCBTbW9rZQ==', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><a class="p_deviceNameText" href="javascript:launchDetailsWindow('VXAgSGFsbCBTbW9rZQ==', 672)">Up Hall Smoke</a>&nbsp; <span class="p_grayNormalText">Zone&nbsp;11</span></td><td class='p_listRow' valign=middle align=right onClick="launchDetailsWindow('VXAgSGFsbCBTbW9rZQ==', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'">Okay&nbsp;</td></tr></tr></table></td></tr>
<tr class="p_rowl" style="cursor:pointer;" onmouseover="setbg(this,'p_rowh')" onmouseout="setbg(this,'p_rowl')"><td><table border=0 cellspacing=0 cellpadding=0 width=100%><tr class='p_listRow'><td width="14" style="overflow: hidden;" class='p_iconCellSummary' onClick="launchDetailsWindow('VXBwZXIgQmVkcm9vbSBCYXRocm9vbQ==', 336)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><span class="devStatIcon" title="Last Event: 12/17&nbsp;11:01&nbsp;AM"><canvas icon="devStatOK" class="p_ic_icon_device" width="13" height="13"></canvas><td width=9 onClick="launchDetailsWindow('VXBwZXIgQmVkcm9vbSBCYXRocm9vbQ==', 336)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><img src="/myhome/20.0.0-244/images/spacer.gif" border=0 width=1 height=2></td><td class='p_listRow' onClick="launchDetailsWindow('VXBwZXIgQmVkcm9vbSBCYXRocm9vbQ==', 336)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><a class="p_deviceNameText" href="javascript:launchDetailsWindow('VXBwZXIgQmVkcm9vbSBCYXRocm9vbQ==', 336)">Upper Bedroom Bathroom</a>&nbsp; <span class="p_grayNormalText">Zone&nbsp;5</span></td><td class='p_listRow' valign=middle align=right onClick="launchDetailsWindow('VXBwZXIgQmVkcm9vbSBCYXRocm9vbQ==', 336)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'">Closed&nbsp;</td></tr></tr></table></td></tr>
```
Looking at the RegEx it appears everything in the table is matched, so not sure why the addon won't start.

**Comment by pickerin** [comment]
I think I figured it out after inspecting the orb.jsp.  It only includes "standard" sensors and not "other devices".  My garage door opener (and sensor), while installed by ADT, do not appear within the orb.jsp.  So, if this is how most addons are now getting status, they'll never work.

**Comment by pickerin** [comment]
Still doesn't explain why the addon won't start at all though...

**Comment by pickerin** [comment]
You can just close this, as I was coming back to using this addon because it worked well.  Understand that ADT is who broke it, thank you for all the hard work.  It's appreciated.

**Comment by digitalcraig** [comment]
I'm happy to still look into why it's not starting since I need to write a test harness which allow me to feed in contributed orb.jsp samples for regression testing anyway. I'm cancelling my ADT monitoring service soon so this will be key to continuing to support the integration for as long as I can or until someone else volunteers to maintain it. I wrote this because I had just signed a contract with ADT when I discovered Home Assistant. That's up now and I'm moving to another monitoring service with official support.

Unfortunately, we can only work with what ADT gives us and HTML scraping has worked pretty well even though it's obviously not supported. Despite promises of allowing open API access, now they are actively discouraging it. There have been reports of ADT blocking IPs and locking people out of their portal accounts.,So far I haven't heard of it happening to anyone using this integration, but that may just be luck.

Sorry I didn't have better news for you.

**Comment by pickerin** [comment]
@digitalcraig Craig, no worries at all.  The community greatly appreciates the efforts (and code) you've provided to keep this going as long as it has.  

If I might ask:
* What are you moving to?
* Are you abandoning your hard-wired sensors as a result?
* Does the new solution provide cellular coverage?

I could abandon mine as well, but the above issues have stopped me so far.  Ease of use for my S.O. is paramount.

**Comment by digitalcraig** [comment]
@pickerin I got a Black Friday deal on Simplisafe which I couldn't pass up. My ADT sensors are already wireless so no change there.  The Simplisafe base has cellular and battery backup if the Internet or power go out. It's more cost up front to buy the components, but the monitoring is cheaper compared to ADT and we calculated it would take 11 months to break-even.
